added RM6175 journey
Crown-Commercial-Service/ccs-scale-decision-tree-db pull request #75
Opened 2022-03-21 10:29 UTC by zubairali6

2022-03-21 16:00 UTC, Chee-Ng requested changes

2022-03-21 16:00 UTC, Chee-Ng commented on graph/RM6175_Records_Information_Management_Service.cypher
> +    (ansGrpSomethingElse)-[:HAS_OUTCOME]->(resultCCSEscapePage)
needs to add `(resultCCSEscapePage:Support {uuid: 'ccb5beb6-75b5-11ea-bc55-0242ac130003'}),` in your match section

2022-03-22 13:25 UTC, zubairali6 commented on graph/RM6175_Records_Information_Management_Service.cypher
> +    (ansGrpSomethingElse)-[:HAS_OUTCOME]->(resultCCSEscapePage)
Should be updated now

2022-03-22 13:32 UTC, Chee-Ng approved these changes

2022-03-22 13:45 UTC, merged